language: Java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: heroku
  api_key:
    secure: J5krY/AnKxm34qRPCXkeVORfia8LzaXDI604rtNAYYLtmwiqYstdIAoBaJUDfMQs2bhsHoFINk97ThWVWnYVgd46E76yXSEJZsOdo9aAjHoyCGhm0TnQYAdQ5jY3IHzftA9fmybMjN0kz6vnIaPWBPXyK7jDQGTG1pZoKtzDFsNiaJNVd8lJqsIKRzvXRtlHvld+TJaqZ3W1PjE3i9eWHyldy7bfa631pNNGBHeV4g1sWRzThe5EjW9n0csUO4dzAoVlWkGliNWZ30e8ZwWgKwqn4KF2v3ruAa5oKIBV8CX+XJGyGOzPDDERqW1/BfeoFJctUVEBhVZ9je1N3gAcZJOOXy+g7TeudKRZx38VxQT8G8hAm+Fitj+Qa4ve4hNt1YBrvkUA5SrsUG0jxeLu3LYSWe4H1yfD95FQrmlVMVIh8WsWog1jDxzcvEIF6U9KRY7314fPpCO1egkh/OIGAcu7RZFv2tyZqdpOeek34ucdmu/gW66nVxLl5SGslHpOlhnVn4qnw+oYiWFpF4PxoLU0TN/7K8XBO6nfW+tn9z6sOl6V2bCp8J1Bdb5UKrcbrfzItx4Q65+Da6hsu5gUI9YWbIVqMiMnqAI/brDc1hG8UxA3fwDjVXSHqPasyn1TblyD9T+c8qPLBErms1HM+Qozr20w4zwn7qCtrGE8sBw=
  app: dominikc-jalgoarena-api
  on:
    repo: dominikc2/JAlgoArena-API
